version: "3.9"

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.15
    container_name: mosquitto_broker
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./data/mosquitto:/mosquitto/data
      - ./logs/mosquitto:/mosquitto/logs
    networks:
      - networkAI

  influxdb:
    image: influxdb:2.6
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=YOUR_ORGANIZATION
      - DOCKER_INFLUXDB_INIT_BUCKET=hydro_data
    volumes:
      - ./data/influxdb:/var/lib/influxdb2
      - ./config/influxdb.conf:/etc/influxdb2/influxdb.conf
    networks:
      - networkAI

  node_red:
    image: nodered/node-red:latest
    container_name: node_red
    restart: unless-stopped
    ports:
      - "1880:1880"
    environment:
      - TZ=Africa/Blantyre
    volumes:
      - ./node_red:/data
    networks:
      - networkAI

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - ./data/grafana:/var/lib/grafana
    networks:
      - networkAI

networks:
    networkAI:
    driver: bridge 
